### ISSUE TITLE
sub-command in airship config module to add/update configuration for document repos

### ISSUE THREAD

**Issue by singhannie** [airshipit/airshipctl#115]
**Problem description (if applicable)**
Command to update the configuration related to manifest repos in airshipctl is required for the below use case: 
(1) user/operator wants to point to a repo from treasuremap to a private repo after adding configuration data for the private repo (for example for security documents).

Workaround, in the absecnce of CLI command, would be to edit the airshipctl config file (~/.airship/config) to update the configuration directly, whereas every user might not be comfortable with editing yaml file directly.

**Proposed change**
Airshipctl config should implement the sub-command for manifest repos so that manifest configuration data for manifest repos in airship config file as depicted below can be updated and added via CLI interface.

_**airshipctl config set-manifest <MANIFEST_NAME> --url <> --user <> --passcode <> --ssh-key <> -- target-path <>**_

```
manifests:
  default:
    primary-repository-name: primary
    repositories:
      primary:
        checkout:
          branch: master
          commit-hash: master
          force: false
          remote-ref: master
          tag: ""
        url: https://opendev.org/airship/treasuremap
    sub-path: treasuremap/manifests/site
    target-path: /tmp/default
  security:
    primary-repository-name: security
    repositories:
      primary:
        checkout:
          branch: master
          commit-hash: master
          force: false
          remote-ref: master
          tag: ""
        url: https://opendev.org/airship/treasuremap
    sub-path: treasuremap/manifests/security
    target-path: /tmp/security
```

**Potential impacts**
It would reduce the need to edit the airship configuration file manually.
