### ISSUE TITLE
sub-command in airship config module to add/update configuration for bootstrapping ephemeral cluster

### ISSUE THREAD

**Issue by singhannie** [airshipit/airshipctl#116]
**Problem description (if applicable)**
Command to update the configuration related to bootstrapinfo in airshipctl is required for the below use cases:  
(1) user/operator wants to update user-data or network data for cloudinit. 
(2) user / operator wants to update the url for iso for the consumption of “remotedirect”.

Workaround, in the absecnce of CLI command, would be to edit the airshipctl config file (~/.airship/config) to update the configuration directly, whereas every user might not be comfortable with editing yaml file directly.

**Proposed change**
Airshipctl config should implement the sub-command for updating bootstrap configuration so that bootstrapInfo in airship config file as depicted below can be updated and added via CLI interface.

_**airshipctl config set-bootstrapinfo <BOOTSTRAPINFO_NAME>  --network-data <> --ssh-key <> -- user-data <> --container-image <> --remote-iso-url <> --remote-type <>**_

“airshipctl confit init” generates below configuration for bootstrap module, and above command would update this configuration, as and when required.
```
modules-config:
  bootstrapInfo:
    default:
      builder:
        networkConfigFileName: network-config
        outputMetadataFileName: output-metadata.yaml
        userDataFileName: user-data
      container:
        containerRuntime: docker
        image: quay.io/airshipit/isogen:latest
        volume: /srv/iso:/config
      remoteDirect:
        isoUrl: http://localhost:8099/debian-custom.iso
        remoteType: redfish
```
**_Note:_** as bootstrapinfo configuration would be a singleton object, it need not be explicitly associated with context via CLI.

**Potential impacts**
It would reduce the need to edit the airship configuration file manually.
