### ISSUE TITLE
Wrong format of network data for ephemeral host

### ISSUE THREAD

**Issue by jingvar** [airshipit/airshipctl#120]
**Describe the bug**
Yaml structure must much network_data.json.

Now is
```
 networkData: |
    network:
      version: 1
      config:
```
Should be like this
```
---
links:
- name: oam0
  type: phy
  id: oam0
  ethernet_mac_address: 52:54:00:ef:fb:eb
networks:
- id: oam0-ipv4
  type: ipv4
  link: oam0
  ip_address: 192.168.100.120
  netmask: 255.255.255.0
  routes:
  - network: 0.0.0.0
    netmask: 0.0.0.0
    gateway: 192.168.100.1
services:
- address: 8.8.8.8
  type: dns
```
