### ISSUE TITLE
Explore cluster-api to understand how we can utilize it with airship yaml documents

### ISSUE THREAD

**Issue by slfletch** [airshipit/airshipctl#123]
**Problem description (if applicable)**
A deeper understanding of how cluster-api works needs to occur in order to determine how airship will be able to utilize it for multiple use cases.

**Proposed change**
Setup a developer environment with Cluster api and Docker Manager
    https://cluster-api.sigs.k8s.io/tasks/installation.html
    https://github.com/kubernetes-sigs/cluster-api/tree/master/bootstrap/kubeadm
    https://github.com/kubernetes-sigs/cluster-api/tree/master/test/infrastructure/docker  (Developer environment) Do not use metal3 as this is not necessary

Introduce etcd encryption manually into your single node cluster 
 ***Notes*** Create document of kind: EncryptionConfiguration and modify the kubeadm.yaml document kind: ClusterConfiguration

Once we understand the steps that need to occur for etcd encryption we need to determine how to enhance the cluster api kubeadm api provider to do the same steps.

After we have obtained how everything fits together and brought this back to the design calls, more issues should be created to look at how does this helps us solve for coredns, and etcd resilience as well as LoadBalancer for the cluster.

**Comment by alexander-hughes** [comment]
Setting up the developer environment is complete, tested, and documented on the Airship blog [here](https://www.airshipit.org/blog/cluster-api-development-environment/)

**Comment by alexander-hughes** [comment]
Following the posted instructions requires a small addition to enable etcd encryption.  In step 10, the clusterconfig is generated via
`clusterctl config cluster work-cluster --kubernetes-version 1.17.0 > work-cluster.yaml`

this clusterconfig can instead be generated manually, with a random etcd encryption key specified via:

```
cat > work-cluster.yaml <<EOF
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerCluster
metadata:
  name: work-cluster
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: work-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.17.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.0.0.0/24
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerCluster
    name: work-cluster
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerMachine
metadata:
  name: controlplane-0
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: work-cluster
    cluster.x-k8s.io/control-plane: "true"
  name: controlplane-0
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
      kind: KubeadmConfig
      name: controlplane-0-config
      namespace: default
  clusterName: work-cluster
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerMachine
    name: controlplane-0
    namespace: default
  version: 1.17.0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfig
metadata:
  name: controlplane-0-config
  namespace: default
spec:
  files:
  - path: "/etc/kubernetes/etcd-encryption.yaml"
    owner: root:root
    permissions: '0640'
    content: |
      ---
      apiVersion: apiserver.config.k8s.io/v1
      kind: EncryptionConfiguration
      resources:
      - resources:
        - secrets
        providers:
        - aescbc:
            keys:
            - name: key1
              secret: $(head -c 32 /dev/urandom | base64)
        - identity: {}
  clusterConfiguration:
    controllerManager:
      extraArgs:
        enable-hostpath-provisioner: 'true'
    apiServer:
      extraArgs:
        encryption-provider-config: "/etc/kubernetes/etcd-encryption.yaml"
      extraVolumes:
      - name: etcd-encryption
        hostPath: "/etc/kubernetes/etcd-encryption.yaml"
        mountPath: "/etc/kubernetes/etcd-encryption.yaml"
  initConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerMachine
metadata:
  name: worker-0
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: work-cluster
  name: worker-0
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
      kind: KubeadmConfig
      name: worker-0-config
      namespace: default
  clusterName: work-cluster
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerMachine
    name: worker-0
    namespace: default
  version: 1.17.0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfig
metadata:
  name: worker-0-config
  namespace: default
spec:
  joinConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
EOF
```

**Comment by alexander-hughes** [comment]
Introducing etcd into cluster via bootstrap provider (CABPK) appears to be handled via the KubeadmConfig object.  Using the above example of cluster configuration generated via clusterctl, the KubeadmConfig object should look similar to this:

```
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfig
metadata:
  name: controlplane-0-config
  namespace: default
spec:
  files:
  - path: "/etc/kubernetes/etcd-encryption.yaml"
    owner: root:root
    permissions: '0640'
    content: |
      ---
      apiVersion: apiserver.config.k8s.io/v1
      kind: EncryptionConfiguration
      resources:
      - resources:
        - secrets
        providers:
        - aescbc:
            keys:
            - name: key1
              secret: $(head -c 32 /dev/urandom | base64)
        - identity: {}
  clusterConfiguration:
    controllerManager:
      extraArgs:
        enable-hostpath-provisioner: 'true'
    apiServer:
      extraArgs:
        encryption-provider-config: "/etc/kubernetes/etcd-encryption.yaml"
      extraVolumes:
      - name: etcd-encryption
        hostPath: "/etc/kubernetes/etcd-encryption.yaml"
        mountPath: "/etc/kubernetes/etcd-encryption.yaml"
  initConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
```
