### ISSUE TITLE
KubeadmControlPlane sets up 'provisioning' bridge, but doesn't persist it

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#160]
**Describe the bug**
Currently the Bridge required by BMO is been configured in the KubeadmControlPlane 

**Steps To Reproduce**
These is an example configuration within the KubeadmControlPlane :
 _**files:
....
 - path: /tmp/interface.sh
        permissions: '0755'
        owner: root:root
        content: |
          #!/bin/bash
          iface=eno4
          bridge=provisioning
          function get_ip_address_from_interface {
            local interface=$1
            local ip=$(ip -4 -o addr s "${interface}" | awk '{ print $4; exit }')
            if [ -z "${ip}" ] ; then
                exit 1
            fi
            echo ${ip}
          }
          ipaddress=$(get_ip_address_from_interface ${iface})
          echo -n "IP Address for ${iface}: " ${ipaddress}
          ip addr del ${ipaddress} dev ${iface}
          ip link set dev ${iface} down
          brctl addbr ${bridge}
          brctl addif ${bridge} ${iface}
          ip addr add ${ipaddress} dev ${bridge}
          ip link set ${bridge} up
          ip link set dev ${iface} up**_

**Expected behavior**
We need this configuration to live across reboots.
In the case of Ubuntu this should be using netplan and approrpiate netplan config file to ensure persistency.

**Environment**
- airshipctl Version:
- Operating System:
- Kernel version:
- Kubernetes Version:
- Go version:
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM):

**Comment by jingvar** [comment]
You can define a bridge with networkData BMH and cloud-init.

**Comment by dukov** [comment]
> You can define a bridge with networkData BMH and cloud-init.

@jingvar could you gibe an example?

**Comment by airshipbot** [comment]
## Related Change [#721778](https://review.opendev.org/721778)

**Subject:** Add control plane deployment with bridge support
**Link:** https://review.opendev.org/721778
**Status:** NEW
**Owner:** Nikolay Fedorov (nfedorov@mirantis.com)

### Approvals
```diff
Code-Review
! None
Verified
! None
Workflow
! None
```

*Last Updated: 2020-04-22 03:30:03 CDT*

**Comment by jingvar** [comment]
```
---
links:
- name: pxe0
  id: pxe0
  type: phy
  ethernet_mac_address: 52:54:00:3b:9a:60
- name: underlay0
  type: phy
  id: underlay0
  ethernet_mac_address: 52:54:00:c6:98:a9
- id: br0
  name: br0
  type: bridge
  bridge_stp: on
  bridge_fd: 0
  bridge_interfaces:
    - underlay0
```
Extra options:

bridge_stp: 
bridge_fd:
bridge_maxwait:
bridge_ageing:
bridge_bridgeprio:
bridge_fd
bridge_gcint: 
bridge_hello: 
bridge_maxage:
bridge_pathcost:
bridge_portprio:
bridge_waitport:
