### ISSUE TITLE
Airshipctl error: missing bootstrapInfo even though it's defined

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#164]
**Describe the bug**

With the following (truncated) config file:
```
contexts:
  default:
    context-kubeconf: default_target
    manifest: default
current-context: default
modules-config:
  bootstrapInfo:
    default:
      builder:
        networkConfigFileName: network-config
        outputMetadataFileName: output-metadata.yaml
        userDataFileName: user-data
      container:
        containerRuntime: docker
        image: quay.io/airshipit/isogen:latest
        volume: /srv/iso:/config
      remoteDirect:
        isoUrl: http://localhost:8099/debian-custom.iso
        remoteType: redfish
```

Airshipctl gives the following error:
```
ubuntu@dev:~$ ./airshipctl bootstrap remotedirect --debug
Missing configuration: No bootstrap-info defined for context "default"
```
