### ISSUE TITLE
Default parameters are overwritten even if they aren't presented in the config file

### ISSUE THREAD

**Issue by vladiskuz** [airshipit/airshipctl#171]
**Describe the bug**
In airshipctl we have default values for some parameters https://github.com/airshipit/airshipctl/blob/master/pkg/config/constants.go
These parameters uses as defaults here https://github.com/airshipit/airshipctl/blob/master/pkg/config/utils.go#L26-L75
When we specify a configuration file, and this file does not contain some parameter, but we have a default value for this particular default parameter, it will not be presented in the result airshipctl configuration.

**Steps To Reproduce**
- Generate default config with `./tools/gate/00_setup.sh && ./tools/gate/22_test_configs.sh`

```
apiVersion: airshipit.org/v1alpha1                                                                                                                                                                                                                    
  clusters:                                                                                                                                                                                                                                             
    dummycluster:                                                                                                                                                                                                                                       
      cluster-type:                                                                                                                                                                                                                                     
        ephemeral:                                                                                                                                                                                                                                      
          bootstrap-info: dummy_bootstrap_config                                                                                                                                                                                                        
          cluster-kubeconf: dummycluster_ephemeral                                                                                                                                                                                                      
  contexts:                                                                                                                                                                                                                                             
    dummy_cluster:                                                                                                                                                                                                                                      
      context-kubeconf: dummy_cluster                                                                                                                                                                                                                   
      manifest: dummy_manifest                                                                                                                                                                                                                          
  current-context: dummy_cluster                                                                                                                                                                                                                        
  kind: Config                                                                                                                                                                                                                                          
  manifests:                                                                                                                                                                                                                                            
    dummy_manifest:                                                                                                                                                                                                                                     
      primary-repository-name: primary                                                                                                                                                                                                                  
      repositories:                                                                                                                                                                                                                                     
        primary:                                                                                                                                                                                                                                        
          checkout:                                                                                                                                                                                                                                     
            branch: "master"                                                                                                                                                                                                                            
            force: false                                                                                                                                                                                                                                
            remote-ref: ""                                                                                                                                                                                                                              
            tag: ""                                                                                                                                                                                                                                     
          url: dummy.url.com                                                                                                                                                                                                                            
      ## this is temporary hack, as soon as we use `document pull` command in gate process                                                                                                                                                              
      ## this will subpath will be airshipctl/manifests/site/test-bootstrap, as airshipctl                                                                                                                                                              
      ## will be primary repository                                                                                                                                                                                                                     
      sub-path: "manifests/site/test-bootstrap"                                                                                                                                                                                                         
      target-path: /home/vk/airshipctl                                                                                                                                                                                                                  
  modules-config:                                                                                                                                                                                                                                       
    bootstrapInfo:                                                                                                                                                                                                                                      
      dummy_bootstrap_config:                                                                                                                                                                                                                           
        container:                                                                                                                                                                                                                                      
          volume: /srv/iso:/config                                                                                                                                                                                                                      
          image: quay.io/airshipit/isogen:latest-debian_stable                                                                                                                                                                                          
          containerRuntime: docker                                                                                                                                                                                                                      
        remoteDirect:                                                                                                                                                                                                                                   
          remoteType: redfish                                                                                                                                                                                                                           
          isoUrl: http://localhost:8099/test.iso                                                                                                                                                                                                        
        builder:                                                                                                                                                                                                                                        
          userDataFileName: user-data                                                                                                                                                                                                                   
          networkConfigFileName: network-config                                                                                                                                                                                                         
          outputMetadataFileName: output-metadata.yaml                                                                                                                                                                                                  
  users:                                                                                                                                                                                                                                                
    dummy_user: {} 
```        
- Modify [DoRemoteDirect()](https://github.com/airshipit/airshipctl/blob/master/pkg/remote/remote_direct.go#L131) for debug purposes like [this](https://github.com/vladiskuz/airshipctl/commit/c0b0a93f917a0359ed8b7e6d9c436068f88b2308?diff=unified): 
```
func (a *Adapter) DoRemoteDirect() error {
	alog.Debugf("Using Remote Endpoint: %q", a.remoteURL)
	alog.Debugf("This is isoUrl param: %q", a.remoteConfig.IsoURL)
	return nil
}
```
- Execute `airshipctl bootstrap remotedirect --debug` to make sure that `isoUrl` is here:
```
$ airshipctl bootstrap remotedirect --debug
2020/04/17 15:17:49 Remote type redfish
2020/04/17 15:17:49 Using Remote Endpoint: "redfish+http://localhost:8000/redfish/v1/Systems/air-ephemeral"
2020/04/17 15:17:49 This is isoUrl param: "http://localhost:8099/test.iso"
```

- Remove parameter that have default value from [constants.go](https://github.com/airshipit/airshipctl/blob/master/pkg/config/constants.go).
 Let's remove `isoURL`. Now the config file look like this:
```
apiVersion: airshipit.org/v1alpha1                                                                                                                                                                                                                    
  clusters:                                                                                                                                                                                                                                             
    dummycluster:                                                                                                                                                                                                                                       
      cluster-type:                                                                                                                                                                                                                                     
        ephemeral:                                                                                                                                                                                                                                      
          bootstrap-info: dummy_bootstrap_config                                                                                                                                                                                                        
          cluster-kubeconf: dummycluster_ephemeral                                                                                                                                                                                                      
  contexts:                                                                                                                                                                                                                                             
    dummy_cluster:                                                                                                                                                                                                                                      
      context-kubeconf: dummy_cluster                                                                                                                                                                                                                   
      manifest: dummy_manifest                                                                                                                                                                                                                          
  current-context: dummy_cluster                                                                                                                                                                                                                        
  kind: Config                                                                                                                                                                                                                                          
  manifests:                                                                                                                                                                                                                                            
    dummy_manifest:                                                                                                                                                                                                                                     
      primary-repository-name: primary                                                                                                                                                                                                                  
      repositories:                                                                                                                                                                                                                                     
        primary:                                                                                                                                                                                                                                        
          checkout:                                                                                                                                                                                                                                     
            branch: "master"                                                                                                                                                                                                                            
            force: false                                                                                                                                                                                                                                
            remote-ref: ""                                                                                                                                                                                                                              
            tag: ""                                                                                                                                                                                                                                     
          url: dummy.url.com                                                                                                                                                                                                                            
      ## this is temporary hack, as soon as we use `document pull` command in gate process                                                                                                                                                              
      ## this will subpath will be airshipctl/manifests/site/test-bootstrap, as airshipctl                                                                                                                                                              
      ## will be primary repository                                                                                                                                                                                                                     
      sub-path: "manifests/site/test-bootstrap"                                                                                                                                                                                                         
      target-path: /home/vk/airshipctl                                                                                                                                                                                                                  
  modules-config:                                                                                                                                                                                                                                       
    bootstrapInfo:                                                                                                                                                                                                                                      
      dummy_bootstrap_config:                                                                                                                                                                                                                           
        container:                                                                                                                                                                                                                                      
          volume: /srv/iso:/config                                                                                                                                                                                                                      
          image: quay.io/airshipit/isogen:latest-debian_stable                                                                                                                                                                                          
          containerRuntime: docker                                                                                                                                                                                                                      
        remoteDirect:                                                                                                                                                                                                                                   
          remoteType: redfish                                                                                                                                                                                                     
        builder:                                                                                                                                                                                                                                        
          userDataFileName: user-data                                                                                                                                                                                                                   
          networkConfigFileName: network-config                                                                                                                                                                                                         
          outputMetadataFileName: output-metadata.yaml                                                                                                                                                                                                  
  users:                                                                                                                                                                                                                                                
    dummy_user: {} 
```

- Execute `airshipctl bootstrap remotedirect --debug` one more time:

```
$ airshipctl bootstrap remotedirect --debug
2020/04/17 15:19:51 Remote type redfish
missing configuration: redfish ephemeral node iso Path empty
```
**Expected behavior**
On the last step we should see the [default value](https://github.com/airshipit/airshipctl/blob/bc5dbed20fef8b004250ebb112d28951ac8f6b5c/pkg/config/constants.go#L51) for `isoUrl`
