### ISSUE TITLE
Invalid ReplacementTransformer error message if pattern not found

### ISSUE THREAD

**Issue by jingvar** [airshipit/airshipctl#191]
**Describe the bug**
If ReplacementTransformer can't find pattern macth it generates message like
"strconv.Atoi: parsing "files[path=konfigadm]": invalid syntax"

**Steps To Reproduce**
config.yaml
```
apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: notImportantHere
replacements:
- source:
    value: 12345678
  target:
    objref:
      kind: KubeadmControlPlane
    fieldrefs:
    - spec.kubeadmConfigSpec.files[path=konfigadm].content%{k8s-version}%
```
test.yaml
```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: cluster-controlplane
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: Metal3MachineTemplate
    name: $(cluster-name)
  kubeadmConfigSpec:
    files:
    - content: |
        kubernetes:
          version: {k8s-version}
        container_runtime:
          type: docker
      owner: root:root
      path: konfigadm_bug_
      permissions: "0640"
```
cat test.yaml | ./airshipctl document plugin config.yaml

**Expected behavior**
Should generate a "pattern '%s' is defined in configuration but was not found in target" message

**Environment**
airshipctl build from commit f555af3bf61f04a1d0948c2922d47e7c89bf5dd5
