### ISSUE TITLE
Airship config mismatch before and after config import.

### ISSUE THREAD

**Issue by sb464f** [airshipit/airshipctl#242]
**Describe the bug**
Airship config before import seems to be as below
apiVersion: airshipit.org/v1alpha1
```
bootstrapInfo:
  default:
    container:
      volume: /data/srv/iso:/config
      image: quay.io/airshipit/isogen:latest-debian_stable
      containerRuntime: docker
    remoteDirect:
      remoteType: redfish-dell
      insecure: true
      useproxy: false
      isoUrl: http://****:8099/iso/debian-custom.iso
    builder:
      userDataFileName: user-data
      networkConfigFileName: network-config
      outputMetadataFileName: output-metadata.yaml
managementConfiguration:
  default:
    type: redfish-dell
    insecure: true
    useproxy: false
    systemActionRetries: 30
    systemRebootDelay: 30
```

Airshipctl config after import seems to be as below:

```
bootstrapInfo:
  default:
    builder:
      networkConfigFileName: network-config
      outputMetadataFileName: output-metadata.yaml
      userDataFileName: user-data
    container:
      containerRuntime: docker
      image: quay.io/airshipit/isogen:latest-debian_stable
      volume: /data/srv/iso:/config
    remoteDirect:
      isoUrl: http://*******:8099/iso/debian-custom.iso
clusters:
  cluster:
    clusterType:
      target:
        bootstrapInfo: default
        clusterKubeconf: cluster_target
        managementConfiguration: default
  dummycluster:
    clusterType:
      ephemeral:
        bootstrapInfo: default
        clusterKubeconf: dummycluster_ephemeral
        managementConfiguration: default
managementConfiguration:
  default:
    insecure: true
    systemActionRetries: 30
    systemRebootDelay: 30
    type: redfish-dell
```

Some config seems to be missing.
So two issues here
1) From config the second seems to be correct, why are we declaring in two places for insecure and redfish type.
2) And config import seems to maintain it's own record of airship/config because it deviates from default airship config

**Steps To Reproduce**
airshipctl config import

**Expected behavior**
Expected to be same before and after config import.

**Environment**
- airshipctl Version:
- Operating System:
- Kernel version:
- Kubernetes Version:
- Go version:
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM):
