### ISSUE TITLE
airshipctl expecting name to be default in .airship/config

### ISSUE THREAD

**Issue by sb464f** [airshipit/airshipctl#244]
**Describe the bug**

```
apiVersion: airshipit.org/v1alpha1
bootstrapInfo:
  dummy_bootstrap_config:
    container:
      volume: /data/srv/iso:/config
      image: quay.io/airshipit/isogen:latest-debian_stable
      containerRuntime: docker
    remoteDirect:
      remoteType: redfish-dell
      insecure: true
      useproxy: false
      isoUrl: http://******:8099/iso/debian-custom.iso
    builder:
      userDataFileName: user-data
      networkConfigFileName: network-config
      outputMetadataFileName: output-metadata.yaml
managementConfiguration:
  dummy_management_config:
    type: redfish-dell
    insecure: true
    useproxy: false
    systemActionRetries: 30
    systemRebootDelay: 30
clusters:
  dummycluster:
    clusterType:
      ephemeral:
        bootstrapInfo: dummy_bootstrap_config
        clusterKubeconf: dummycluster_ephemeral
        managementConfiguration: dummy_management_config
```

This config isn't helping airshipctl to use the parameters that are passed in config for iso_url redfish type, etc..
when changing bootstrapInfo name to default then working fine. the below config works

```
apiVersion: airshipit.org/v1alpha1
bootstrapInfo:
  default:
    container:
      volume: /data/srv/iso:/config
      image: quay.io/airshipit/isogen:latest-debian_stable
      containerRuntime: docker
    remoteDirect:
      remoteType: redfish-dell
      insecure: true
      useproxy: false
      isoUrl: http://*****:8099/iso/debian-custom.iso
    builder:
      userDataFileName: user-data
      networkConfigFileName: network-config
      outputMetadataFileName: output-metadata.yaml
managementConfiguration:
  default:
    type: redfish-dell
    insecure: true
    useproxy: false
    systemActionRetries: 30
    systemRebootDelay: 30
clusters:
  dummycluster:
    clusterType:
      ephemeral:
        bootstrapInfo: default
        clusterKubeconf: dummycluster_ephemeral
        managementConfiguration: default
```
So something is hardcoded to looks for default value probably..?

**Steps To Reproduce**
any airshipctl env with custom name for bootstarp and management config

**Expected behavior**
Expected to use values passed in .airship/config

**Environment**
- airshipctl Version:
- Operating System:
- Kernel version:
- Kubernetes Version:
- Go version:
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM):
