### ISSUE TITLE
Variable Substitution not working during execution of "airshipctl cluster init"

### ISSUE THREAD

**Issue by sshiba** [airshipit/airshipctl#284]
**Describe the bug**
The Azure `manifest/function/capz/<version>default/credentials.yaml` file includes four Azure subscription credential variables: `AZURE_SUBSCRIPTION_ID_B64`, `AZURE_TENANT_ID_B64`,` AZURE_CLIENT_ID_B64`, and `AZURE_CLIENT_SECRET_B64`. @KALYNOVSKYI, KOSTIANTYN

In the Cluster API, the values for these variables can be provided through environment variables or config file.
The issue is that the Azure variables in the `credentials.yaml` file are not substituted and causing an error when initializing `capz `components during the execution of `airshipctl cluster init` command.

**Steps To Reproduce**
Execute `airshipctl cluster init` with airship config file referencing a test site that includes Azure component (see below). Also, need to have CAPZ manifests added, i.e., `manifest/function/capz/v0.4.5`, which includes the `credentials.yaml` file.

```
 apiVersion: airshipit.org/v1alpha1
kind: Clusterctl
metadata:
  labels:
    airshipit.org/deploy-k8s: "false"
  name: clusterctl-v1
init-options:
...
  infrastructure-providers:
    - "azure:v0.4.5"
providers:
  - name: "azure"
    type: "InfrastructureProvider"
    versions:
      v0.4.5: airshipctl/manifests/function/capz/v0.4.5
...
```

**Expected behavior**
Expecting to substitute the Azure variables in the `credentials.yaml` file (see below) during the execution of the command `airshipctl cluster init`. 

```
apiVersion: v1
kind: Secret
metadata:
  name: manager-bootstrap-credentials
  namespace: system
type: Opaque
data:
  subscription-id: ${AZURE_SUBSCRIPTION_ID_B64}
  tenant-id: ${AZURE_TENANT_ID_B64}
  client-id: ${AZURE_CLIENT_ID_B64}
  client-secret: ${AZURE_CLIENT_SECRET_B64}
```

**Environment**
- airshipctl Version: 2.0
- Operating System: Unbunt 18.04
- Kernel version:
- Kubernetes Version: kind version 0.9.0-alpha 
- Go version: go1.14.4 linux/amd64
- Hardware specs: VirtulBox VM, 4 vCPUs, 8GB RAM, 40GB Disk
