### ISSUE TITLE
YAML: Duplicated YAML keys

### ISSUE THREAD

**Issue by alexander-hughes** [airshipit/airshipctl#311]
**Describe the bug**
Duplicate YAML keys for some linters will warn, for others they will throw an error. It is incorrect to duplicate a YAML key.

**Steps To Reproduce**
Tools like https://github.com/adrienverge/yamllint can be used to scan for YAML linting errors, including duplicate keys.

At the time of creating this issue there is only one duplicate key:
cmd/cluster/testdata/statusmap/legacy-crd.yaml:metadata
```
# this is a legacy CRD which defines a type whose status can be checked using
# the condition in the annotations
# It is included in tests to assure backward compatibility
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
metadata:
  name: legacies.example.com
  annotations:
```

**Expected behavior**
Remove duplicate YAML keys so that YAML linting will be successful.

**Environment**
- airshipctl Version:
- Operating System:
- Kernel version:
- Kubernetes Version:
- Go version:
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM):
