### ISSUE TITLE
Can't delete fields using `config set-X`

### ISSUE THREAD

**Issue by ian-howell** [airshipit/airshipctl#348]
Given the below config file, there is currently no way to use the `airshipctl config` command to delete a field. In this case, a user may want to delete the `server` field, and might attempt to do so using the command `airshipctl config set-cluster --server=""`. Currently, this command would do nothing, since our code only checks for the empty string before setting a new value.

```
apiVersion: v1
clusters:
- cluster:
    server: https://172.17.0.1:6443
  name: default_target
```

~I suggest modifying the `config.ModifyX` commands to replace their `Options` parameter with a `pflag.FlagSet` parameter, as this would allow us to check whether a given flag has be set via the [Changed](https://github.com/spf13/pflag/blob/master/flag.go#L515) function.~

This issue may also involve deleting the mentioned `Options` types.
