### ISSUE TITLE
Inaccurate output for incomplete phase documents

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#365]
**Steps To Reproduce**
When a user defines an incomplete phase document, e.g.

```
---
apiVersion: airshipit.org/v1alpha1
kind: Phase
metadata:
  name: custom-phase-target
  clusterName: target-cluster
config:
  documentEntryPoint: path/to/example/entrypoint
```

and the user performs a document render using `airshipctl phase render custom-phase-target`, the error output is `document filtered by selector No selection conditions specified found more than one document`.

**Expected behavior**
The error should inform the user that the phase document is missing required fields or is malformatted.
