### ISSUE TITLE
Phase run control plane gets stuck with docker provider

### ISSUE THREAD

**Issue by rkjain** [airshipit/airshipctl#413]
**Description**

airshipctl phase run control-plane  with docker provider is not working with the latest code.
It gets stuck while deploying control plane. However, this is working fine, if I checkout a commit from Nov 10 (9c9369088c26e2fc7cea200e78a2966a3c173d68) - "Change image tags"

**Steps To Reproduce**

airshipctl phase run controlplane-ephemeral --debug --kubeconfig ~/.airship/kubeconfig
```
[airshipctl] 2020/11/13 10:37:36 opendev.org/airship/airshipctl@/pkg/k8s/applier/executor.go:129: Getting kubeconfig context name from cluster map
[airshipctl] 2020/11/13 10:37:36 opendev.org/airship/airshipctl@/pkg/k8s/applier/executor.go:134: Getting kubeconfig file information from kubeconfig provider
[airshipctl] 2020/11/13 10:37:36 opendev.org/airship/airshipctl@/pkg/k8s/applier/executor.go:139: Filtering out documents that shouldn't be applied to kubernetes from document bundle
[airshipctl] 2020/11/13 10:37:36 opendev.org/airship/airshipctl@/pkg/k8s/applier/executor.go:147: Using kubeconfig at '/home/rishabh/.airship/kubeconfig' and context 'ephemeral-cluster'
[airshipctl] 2020/11/13 10:37:36 opendev.org/airship/airshipctl@/pkg/k8s/applier/executor.go:118: WaitTimeout: 33m20s
[airshipctl] 2020/11/13 10:37:36 opendev.org/airship/airshipctl@/pkg/k8s/applier/applier.go:76: Getting infos for bundle, inventory id is controlplane-ephemeral
[airshipctl] 2020/11/13 10:37:36 opendev.org/airship/airshipctl@/pkg/k8s/applier/applier.go:106: Inventory Object config Map not found, auto generating Inventory object
[airshipctl] 2020/11/13 10:37:36 opendev.org/airship/airshipctl@/pkg/k8s/applier/applier.go:113: Injecting Inventory Object: {"apiVersion":"v1","kind":"ConfigMap","metadata":{"creationTimestamp":null,"labels":{"cli-utils.sigs.k8s.io/inventory-id":"controlplane-ephemeral"},"name":"airshipit-controlplane-ephemeral","namespace":"airshipit"}}{nsfx:false,beh:unspecified} into bundle
[airshipctl] 2020/11/13 10:37:36 opendev.org/airship/airshipctl@/pkg/k8s/applier/applier.go:119: Making sure that inventory object namespace airshipit exists
cluster.cluster.x-k8s.io/target-cluster created
dockercluster.infrastructure.cluster.x-k8s.io/target-cluster created
dockermachinetemplate.infrastructure.cluster.x-k8s.io/target-cluster-control-plane created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/target-cluster-control-plane created
machinehealthcheck.cluster.x-k8s.io/target-cluster-mhc-0 created
5 resource(s) applied. 5 created, 0 unchanged, 0 configured
dockermachinetemplate.infrastructure.cluster.x-k8s.io/target-cluster-control-plane is NotFound: Resource not found
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/target-cluster-control-plane is NotFound: Resource not found
machinehealthcheck.cluster.x-k8s.io/target-cluster-mhc-0 is NotFound: Resource not found
cluster.cluster.x-k8s.io/target-cluster is NotFound: Resource not found
dockercluster.infrastructure.cluster.x-k8s.io/target-cluster is NotFound: Resource not found
cluster.cluster.x-k8s.io/target-cluster is InProgress: 
dockercluster.infrastructure.cluster.x-k8s.io/target-cluster is Current: Resource is current
dockermachinetemplate.infrastructure.cluster.x-k8s.io/target-cluster-control-plane is Current: Resource is current
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/target-cluster-control-plane is Current: Resource is current
machinehealthcheck.cluster.x-k8s.io/target-cluster-mhc-0 is Current: Resource is current
```
Gets stuck here ..
After some time throws this
```
[airshipctl] 2020/11/13 16:54:06 opendev.org/airship/airshipctl/pkg/events/processor.go:77: Received error when applying errors to kubernetes timeout after 2000 seconds waiting for 5 resources to reach condition AllCurrent
Error events received on channel, errors are:
[timeout after 2000 seconds waiting for 5 resources to reach condition AllCurrent]
```

**Expected behavior**

airshipctl phase run controlplane-ephemeral --debug --kubeconfig ~/.airship/kubeconfig

```
❯ airshipctl phase run controlplane-ephemeral --debug --kubeconfig ~/.airship/kubeconfig
[airshipctl] 2020/11/05 16:31:53 opendev.org/airship/airshipctl/pkg/k8s/applier/executor.go:126: Getting kubeconfig file information from kubeconfig provider[airshipctl] 2020/11/05 16:31:53 opendev.org/airship/airshipctl/pkg/k8s/applier/executor.go:131: Filtering out documents that shouldn't be applied to kubernetes from document bundle
[airshipctl] 2020/11/05 16:31:53 opendev.org/airship/airshipctl/pkg/k8s/applier/executor.go:115: WaitTimeout: 33m20s
[airshipctl] 2020/11/05 16:31:53 opendev.org/airship/airshipctl/pkg/k8s/applier/applier.go:76: Getting infos for bundle, inventory id is controlplane-ephemeral
[airshipctl] 2020/11/05 16:31:53 opendev.org/airship/airshipctl/pkg/k8s/applier/applier.go:106: Inventory Object config Map not found, auto generating Inventory object
[airshipctl] 2020/11/05 16:31:53 opendev.org/airship/airshipctl/pkg/k8s/applier/applier.go:113: Injecting Inventory Object: {"apiVersion":"v1","kind":"ConfigMap","metadata":{"creationTimestamp":null,"labels":{"cli-utils.sigs.k8s.io/inventory-id":"controlplane-ephemeral"},"name":"airshipit-controlplane-ephemeral","namespace":"airshipit"}}{nsfx:false,beh:unspecified} into bundle
[airshipctl] 2020/11/05 16:31:53 opendev.org/airship/airshipctl/pkg/k8s/applier/applier.go:119: Making sure that inventory object namespace airshipit exists
cluster.cluster.x-k8s.io/target-cluster created
dockercluster.infrastructure.cluster.x-k8s.io/target-cluster created
dockermachinetemplate.infrastructure.cluster.x-k8s.io/target-cluster-control-plane created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/target-cluster-control-plane created
machinehealthcheck.cluster.x-k8s.io/target-cluster-mhc-0 created
5 resource(s) applied. 5 created, 0 unchanged, 0 configured
dockermachinetemplate.infrastructure.cluster.x-k8s.io/target-cluster-control-plane is NotFound: Resource not found
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/target-cluster-control-plane is NotFound: Resource not found
machinehealthcheck.cluster.x-k8s.io/target-cluster-mhc-0 is NotFound: Resource not found
cluster.cluster.x-k8s.io/target-cluster is NotFound: Resource not found
dockercluster.infrastructure.cluster.x-k8s.io/target-cluster is NotFound: Resource not found
cluster.cluster.x-k8s.io/target-cluster is InProgress: 
dockercluster.infrastructure.cluster.x-k8s.io/target-cluster is Current: Resource is Ready
dockermachinetemplate.infrastructure.cluster.x-k8s.io/target-cluster-control-plane is Current: Resource is current
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/target-cluster-control-plane is Current: Resource is current
machinehealthcheck.cluster.x-k8s.io/target-cluster-mhc-0 is Current: Resource is current
cluster.cluster.x-k8s.io/target-cluster is InProgress: Scaling up to 1 replicas (actual 0)
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/target-cluster-control-plane is InProgress: Scaling up to 1 replicas (actual 0)
cluster.cluster.x-k8s.io/target-cluster is Current: Resource is Ready
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/target-cluster-control-plane is Current: Resource is Ready
all resources has reached the Current status


❯ kubectl get machines --kubeconfig ~/.airship/kubeconfig
NAME                                 PROVIDERID                                      PHASE
target-cluster-control-plane-d9pgc   docker:////target-cluster-control-plane-d9pgc   Running
```

Also check:  https://hackmd.io/poGGfCNGTVeR8Yr28MYXNA for using docker provider.

**Comment by teoyaomiqui** [comment]
@rkjain This means that some resources are not reaching desired state, can you please paste output describing all objects in kubernetes that are delivered in this phase?

**Comment by rkjain** [comment]
Yeah. Here you go
❯ airshipctl phase render controlplane-ephemeral
```
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: target-cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.17.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.0.0.0/24
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: target-cluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerCluster
    name: target-cluster
...
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineHealthCheck
metadata:
  name: target-cluster-mhc-0
spec:
  clusterName: target-cluster
  maxUnhealthy: 100%
  selector:
    matchLabels:
      nodepool: pool1
  unhealthyConditions:
  - status: "True"
    timeout: 30s
    type: E2ENodeUnhealthy
...
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: target-cluster-control-plane
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerMachineTemplate
    name: target-cluster-control-plane
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    files:
    - content: |
        #!/bin/sh -x
        su - root -c "sleep 10; kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/v3.12/manifests/calico.yaml"
      owner: root:root
      path: /calico.sh
      permissions: "0755"
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    postKubeadmCommands:
    - sh /calico.sh
  replicas: 1
  version: v1.18.6
...
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerCluster
metadata:
  name: target-cluster
...
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerMachineTemplate
metadata:
  name: target-cluster-control-plane
spec:
  template:
    spec:
      extraMounts:
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock
…
```
