### ISSUE TITLE
controlplane-target using old metal3machinetemplate object moved from ephemeral

### ISSUE THREAD

**Issue by sb464f** [airshipit/airshipctl#421]
**Describe the bug**
kubeadmcontrolplane uses metal3machinetemplate as reference for qcow image url. and when kubeadmcontrolplane was scaled in target controlplane it is using the metal3machinetemplate that was moved from ephemeral cluster earlier. 

`
  Normal  ProvisioningError       24s    metal3-baremetal-controller  host validation error: Validation of image href http://172.30.0.140:80/images/ubuntu-18.04-server-cloudimg-amd64.img failed, reason: HTTPConnectionPool(host='172.30.0.140', port=80): Max retries exceeded with url: /images/ubuntu-18.04-server-cloudimg-amd64.img (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff04e7a8be0>: Failed to establish a new connection: [Errno 113] EHOSTUNREACH',)); Validation of image href http://172.30.0.140:80/images/ubuntu-18.04-server-cloudimg-amd64.img failed, reason: HTTPConnectionPool(host='172.30.0.140', port=80): Max retries exceeded with url: /images/ubuntu-18.04-server-cloudimg-amd64.img (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff04e874860>: Failed to establish a new connection: [Errno 113] EHOSTUNREACH',))
`
it was supposed to use `172.30.0.145` which was new metal3machine template. As a workaround bouncing the controlplane machine which will create a new machine referencing new metal3machinetemplate fixes the issue.

ephemeral m3mtemplate :- 
```
apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  name: versions-airshipctl
files:
  k8scontrol:
    cluster_controlplane_image:
      url: http://172.30.0.140:80/images/ubuntu-18.04-server-cloudimg-amd64.img
      checksum: "0c53acf0840cfe4d675629c5a8b9c79b"
```

target m3mtemplate:-

```
apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  name: versions-airshipctl
files:
  k8scontrol:
    cluster_controlplane_image:
      url: http://172.30.0.145:80/images/ubuntu-18.04-server-cloudimg-amd64.img
      checksum: "0c53acf0840cfe4d675629c5a8b9c79b"
```

**Steps To Reproduce**
use different url for qcow reference in ephemeral and target cluster, perform a cluster move of objects, and apply target controlplane.

**This is an intermittent issue**

**Expected behavior**
`
  Normal  ProvisioningStarted  28s   metal3-baremetal-controller  Image provisioning started for http://172.30.0.145:80/images/ubuntu-18.04-server-cloudimg-amd64.img
`
