### ISSUE TITLE
Regex support to templater

### ISSUE THREAD

**Issue by SirishaGopigiri** [airshipit/airshipctl#438]
**Problem description (if applicable)**
Adding regex feature to the templater krm-function helps create strings based on the regular expression specified

**Proposed change**
The changes will be added to the templater go code which would help create passphrases based on regular expression.

Usage:

```
apiVersion: airshipit.org/v1alpha1
kind: Templater
metadata:
  name: notImportantHere
values:
  regex: "^[a-z]{5,10}$"
  limit: 10
template: |
  password: {{ regexGen .regex (.limit|int) }}
```

Output:
```
password: rtucfg
```
