### ISSUE TITLE
Default airship config values getting added to user-specified config

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/airshipctl#447]
Somehow the hardcoded default airshipctl config file values, which are intended to be used when no config file (yet) exists, are also being mixed into a user's config file values at runtime when the file does exist.

As an example, when testing `airshipctl cluster list` from the following patchset, I get the error:
"open /tmp/default/treasuremap/manifests/site/test-site/metadata.yaml: no such file or directory"
even though I have no reference to /tmp/default in my airship config file.
https://review.opendev.org/c/airship/airshipctl/+/769327

I know @matthew-fuller has also seen this behavior cause issues in a different context when using AirshipUI.

**Comment by uberscott** [comment]
I'd like to take this one on.  it might be a good way to learn the system.

**Comment by uberscott** [comment]
@mattmceuen if you can assign to me.

**Comment by ak3216** [comment]
@uberscott all yours.

**Comment by kozhukalov** [comment]
`cluster list` command relies on the cluster map object defined in the manifests https://github.com/airshipit/airshipctl/blob/master/manifests/phases/cluster-map.yaml
If config file already exists, it must properly define the path to the manifests. 
The problem at the moment is that by default the config file is initialized with the following manifests field
```
manifests:
  default:
    inventoryRepositoryName: primary
    metadataPath: manifests/site/test-site/metadata.yaml
    phaseRepositoryName: primary
    repositories:
      primary:
        checkout:
          branch: master
          commitHash: ""
          force: false
          localBranch: false
          tag: ""
        url: https://opendev.org/airship/treasuremap
    targetPath: /tmp/default
```
and https://opendev.org/airship/treasuremap repository does not even contain the metadata.yaml. 
The possible solution could be to initialize the config file with the https://opendev.org/airship/airshipctl repository, which is the only repository at the moment which contains proper manifests (which we use for gating).
