### ISSUE TITLE
GenericContainer Executor Enhancements for Privileged Container

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#458]
**Proposed change**
Need a new GenericContainer executor or extend current implementation for airshipctl that would be able to launch privileged containers and have absolute path mounts, to help integrate image builder.

**Comment by teoyaomiqui** [comment]
related patchset https://review.opendev.org/c/airship/airshipctl/+/774161

**Comment by teoyaomiqui** [comment]
related patchset https://review.opendev.org/c/airship/airshipctl/+/774156/2

**Comment by teoyaomiqui** [comment]
patchset that would close the issue: https://review.opendev.org/c/airship/airshipctl/+/774503

**Comment by airshipbot** [comment]
A [Related Change](https://review.opendev.org/774156 was merged. This issue may be ready to close.

**Comment by airshipbot** [comment]
A [Related Change](https://review.opendev.org/774384 was merged. This issue may be ready to close.

**Comment by teoyaomiqui** [comment]
Generic container interface was extended with a new, default type, airship and now it can be used in privileged mode and mounts can be specified as well.

```yaml
apiVersion: airshipit.org/v1alpha1
kind: GenericContainer
metadata:
  name: builder
  labels:
    airshipit.org/deploy-k8s: "false"
spec:
  type: airship
  sinkOutputDir: "target/generator/results/generated"
  image: builder1
  envVars:
  - MYVAR1=my-value
  - MYVAR # pass through host variable
  hostNetwork: true
  mounts:
  - type: bind
    src: /home/ubuntu/mounts
    dst: /my-mounts
    rw: true
  airship:
    privileged: true
    cmd: "/my-command"
config: |
  apiVersion: v1
  kind: ConfigMap
  data:
    my-container-action: build
    format: qcow2
```

Easiest way to access this `config` field from the executor definition is to use go framework that is designed specifically for working with this format:

- **Example**: https://review.opendev.org/c/airship/airshipctl/+/773678/7/krm-functions/kubectl/main.go
- **Source code**: https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/fn/framework

patchset https://review.opendev.org/c/airship/airshipctl/+/774503 was merged issue can be closed now.
