### ISSUE TITLE
extend kubeconfig support in phases

### ISSUE THREAD

**Issue by teoyaomiqui** [airshipit/airshipctl#460]
**Problem description (if applicable)**
As discussed multiple times on the design calls, airshipctl needs further kubeconfig integration into phases and phase plan:
This is needed to make sure that `# airshipctl plan run` can run seamlessly end to end.

Without this airshipctl appears to be incomplete and unfinished tool with a bunch of workarounds.

Such cases as 
- **kubeconfig from KIND** cluster should be supported without specifying any flags to `# airshipctl phase/plan run command`
- **kubeconfig from public clouds** should be supported without any specific flags supplied to the  `# airshipctl phase/plan run command`
- **kubeconfig accesible inside generic containers** - [related patchset](https://review.opendev.org/c/airship/airshipctl/+/773536)

**Proposed change**

1. Extend further [kubeconfig builder](https://github.com/airshipit/airshipctl/blob/master/pkg/k8s/kubeconfig/builder.go#L76-L96) functionality to build one holistic site kubeconfig that would encompass all kubeconfigs from all bundle/filesystem/cluster-api/other-source.
2. Extend [ClusterMap interface](https://github.com/airshipit/airshipctl/blob/master/pkg/cluster/clustermap/map.go#L28-L34) based on ClusterMapAPI [object](https://github.com/airshipit/airshipctl/blob/master/pkg/api/v1alpha1/cluster_map_types.go) to embed information about kubeconfig source, example:
```yaml
---
apiVersion: airshipit.org/v1alpha1
kind: ClusterMap
metadata:
  labels:
    airshipit.org/deploy-k8s: "false"
  name: main-map
map:
  target-cluster:
    parent: ephemeral-cluster
    kubeconfigContext: target-override-context
    kubeconfigSources:
      - type: filesystem
         path: ~/.airship/kubeconfig
         context: target-context
      - type: clusterAPI
         clusterAPIRef:
           - name: target-cluster
              namespace: default
              parentCluster: ephemeral-cluster
      - type: bundle
         name: target-kubeconfig
         namespace: ""
         context: my-target-context
      - type: S3
         bucket: ...
         ref: ...
      - type: genericContainer
         ref:
           name: mygenericContainer
  ephemeral-cluster:
    kubeconfigSources:
    - type: filesystem
       path: ~/.airshipctl/kubeconfig
       context: ephemeral-context
```
In the case if we adapt a slice of sources `KubeconfigSources []KubeconfigSource` airshipctl would be able to scan these sources in ordered manner until finds existing source and use it compile one **site kubeconfig**. Imagine scenario where you have a **KIND** cluster that is used as ephemeral cluster, to which kubeconfig can not be predefined and **azure** target cluster to which deployer has credentials defined in ENVVARS. A deployer would have a cluster map such as this:

```yaml
---
apiVersion: airshipit.org/v1alpha1
kind: ClusterMap
metadata:
  name: main-map
map:
  target-cluster:
    kubeconfigSources:
    - type: cluster-api
       clusterAPIref:
         name: target
         namespace: default
    - type: azureBlobs
       container: my-cont
       blob: target-kubeconfig
  ephemeral-cluster:
    kubeconfigContext: ephemeral-override-context
    kubeconfigSources:
    - type: filesystem
       path: /kind/bind/volume
       context: ephemeral-context # this is predictable context name
```
the following steps would be performed: 
1. **bootstrap KIND executor** writes the kubeconfig to the specified place on filesystem `/kind/bind/volume` and it is available to other executors since this point.
2. **target cluster is deployed** to Azure via cluster-api in KIND ephemeral cluster  
3. **generic container executor** or newly developed `first class citizen` executor writes the kubeconfig to azure blob storage, or this step is done manually by a deployer, airshipctl can easily support either of these cases.
4. **greenfield plan is run successfully**
5. **brownfield plan is being run** and its executors need access to target cluster
6. **airshipctl looks for a kubeconfig** to access target-cluster
7. airshipctl looks at the **first kubeconfig source cluster-api** - not reachable, because **ephemeral cluster** is teared **down**.
8. airshipctl looks at the **second kubeconfig source azure blob**  - **kubeconfig is found**, now we can run a phase.

No manifests need to be modified, and `# airshipctl plan run` doesn't have to be stopped to write save kubeconfig to manifests or anywhere else. Clustermap stays the same. this cluster map from case above, persist the same for every site of this type, same goes for baremetal sites, and same goes for capg, capd sites. Users dont need to be aware of this cluster-map, only if they want to add new clusters, for this case we need a well defined documentation anyway.

And with this approach it will be easy to extend new sources if needed, such as public clouds, object storages or secret storages, like barbican or hashi corp vault, or even a krm function that will return kubeconfig as output.

While this seems to be a complicated way to keep the track of the cluster kubeconfigs, this maps will be pretty static, and included by each site type, and there will be almost need to manage it. On top of this, in future, we can develop autodiscovery mode, where kubeconfigs maybe autodiscovered if the sources follow well defined API.

As an alternative, we have to develop more complicated scripts to keep track of the contexts and manifests, this job lays solely on the shoulders of the deployers and developer and done chaotically in uncontrollable fashion, making it hard to maintain and understand, examples how it has to handled now.
