### ISSUE TITLE
airshipctl config get-context must show which of the contexts is current if there are more than one contexts

### ISSUE THREAD

**Issue by kozhukalov** [airshipit/airshipctl#475]
**Problem description (if applicable)**
`airshipctl config get-context` gets something like this if there are two config contexts
```
contextKubeconf: ""
managementConfiguration: foo
manifest: bar

contextKubeconf: ""
managementConfiguration: xxx
manifest: yyy
```

**Proposed change**
It must be possible to see which of the shown contexts is currently in use.

**Potential impacts**
No

**Comment by kozhukalov** [comment]
Small and easy to fix.

**Comment by ChumkiDas** [comment]
I would like to work on it. Please assign it to me.

**Comment by ak3216** [comment]
@ChumkiDas all yours. Vladimir had indicated this was a small effort, so I added that label. If you find it's more involved, let me know & I'll update. Thaks.

**Comment by ChumkiDas** [comment]
@kozhukalov  Can you please confirm if the below result is what you are expecting?

contextKubeconf: ""
managementConfiguration: default
manifest: default

contextKubeconf: ""
managementConfiguration: xxx
manifest: yyy

Current context:  default

**Comment by ChumkiDas** [comment]
Hi @kozhukalov Could you please reply to my previous post?Once confirmed, I can proceed with the next steps.

**Comment by StevTheDev** [comment]
I think it would be nice if this command displayed the name of the contexts too. See how they're shown in the airship config file?

```
apiVersion: airshipit.org/v1alpha1
contexts:
  default:
    contextKubeconf: ""
    managementConfiguration: default
    manifest: default
  ephemeral-cluster:
    contextKubeconf: ephemeral-cluster_ephemeral
    managementConfiguration: dummy_management_config
    manifest: treasuremap_ci
  target-cluster:
    contextKubeconf: target-cluster_target
    managementConfiguration: dummy_management_config
    manifest: treasuremap_ci
currentContext: target-cluster
```
