### ISSUE TITLE
`airshipctl document pull` does not work if a repo has a detached HEAD

### ISSUE THREAD

**Issue by StevTheDev** [airshipit/airshipctl#479]
**Describe the bug**
`airshipctl document pull` does not work if a repo has a detached HEAD.

**Steps To Reproduce**

- Have a detached head (eg from Gerrit PS Checkout)
```
steven@airship-2:~/treasuremap$ git status
HEAD detached at FETCH_HEAD
nothing to commit, working tree clean
steven@airship-2:~/treasuremap$ git log
commit 258b58add93e58e6756c22c2541af1494db4d128 (HEAD)
...
```
- Observe the correct SHA in the config generated by gating script `22_test_configs.sh`
```
  treasuremap_ci:
    inventoryRepositoryName: primary
    metadataPath: manifests/site/test-site/metadata.yaml
    phaseRepositoryName: primary
    repositories:
      airshipctl:
        checkout:
          branch: ""
          commitHash: 5820e22d9f436df2f93d8b71286b2ad0492279bc
          force: false
          localBranch: false
          tag: ""
        url: https://opendev.org/airship/airshipctl.git
      primary:
        checkout:
          branch: ""
          commitHash: 258b58add93e58e6756c22c2541af1494db4d128
          force: false
          localBranch: false
          tag: ""
        url: /home/steven/treasuremap
    targetPath: /tmp/default
```
- Run `airshipctl document pull --debug` and observe `reference not found`
```
steven@airship-2:~/treasuremap$ airshipctl document pull --debug
[airshipctl] 2021/03/08 15:29:15 opendev.org/airship/airshipctl@/pkg/document/pull/pull.go:36: Reading current context manifest information from /home/steven/.airship/config
[airshipctl] 2021/03/08 15:29:15 opendev.org/airship/airshipctl@/pkg/document/pull/pull.go:51: Downloading airshipctl repository airshipctl from https://opendev.org/airship/airshipctl.git into /tmp/default
[airshipctl] 2021/03/08 15:29:15 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:141: Attempting to download the repository airshipctl
[airshipctl] 2021/03/08 15:29:15 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:126: Attempting to clone the repository airshipctl from https://opendev.org/airship/airshipctl.git
[airshipctl] 2021/03/08 15:29:19 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:110: Attempting to checkout the repository airshipctl from commit hash 5820e22d9f436df2f93d8b71286b2ad0492279bc
[airshipctl] 2021/03/08 15:29:19 opendev.org/airship/airshipctl@/pkg/document/pull/pull.go:51: Downloading primary repository treasuremap from /home/steven/treasuremap into /tmp/default
[airshipctl] 2021/03/08 15:29:19 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:141: Attempting to download the repository treasuremap
[airshipctl] 2021/03/08 15:29:19 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:126: Attempting to clone the repository treasuremap from /home/steven/treasuremap
unexpected client error: reference not found
```

- Attach the HEAD to some branch `git checkout -b asdfasdfas` and rerun the command:
```
steven@airship-2:~/treasuremap$ git checkout -b asdfasdfas
Switched to a new branch 'asdfasdfas'
steven@airship-2:~/treasuremap$ sudo rm -rf /tmp/default/
steven@airship-2:~/treasuremap$ airshipctl document pull --debug
[airshipctl] 2021/03/08 15:31:05 opendev.org/airship/airshipctl@/pkg/document/pull/pull.go:36: Reading current context manifest information from /home/steven/.airship/config
[airshipctl] 2021/03/08 15:31:05 opendev.org/airship/airshipctl@/pkg/document/pull/pull.go:51: Downloading airshipctl repository airshipctl from https://opendev.org/airship/airshipctl.git into /tmp/default
[airshipctl] 2021/03/08 15:31:05 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:141: Attempting to download the repository airshipctl
[airshipctl] 2021/03/08 15:31:05 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:126: Attempting to clone the repository airshipctl from https://opendev.org/airship/airshipctl.git
[airshipctl] 2021/03/08 15:31:08 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:110: Attempting to checkout the repository airshipctl from commit hash 5820e22d9f436df2f93d8b71286b2ad0492279bc
[airshipctl] 2021/03/08 15:31:08 opendev.org/airship/airshipctl@/pkg/document/pull/pull.go:51: Downloading primary repository treasuremap from /home/steven/treasuremap into /tmp/default
[airshipctl] 2021/03/08 15:31:08 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:141: Attempting to download the repository treasuremap
[airshipctl] 2021/03/08 15:31:08 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:126: Attempting to clone the repository treasuremap from /home/steven/treasuremap
[airshipctl] 2021/03/08 15:31:09 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:110: Attempting to checkout the repository treasuremap from commit hash 258b58add93e58e6756c22c2541af1494db4d128
steven@airship-2:~/treasuremap$
```

**Expected behavior**
`airshipctl document pull` resolves the `commitHash` specified in the `checkout` section

**Environment**
- airshipctl Version: `master`
- Operating System: Ubuntu 18.04.5 LTS
- Kernel version: 4.15.0-136-generic
- Kubernetes Version: v1.18.6
- Go version: go1.13.9
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM):
    - VM
    - 8 vCPU
    - 24GB RAM
