### ISSUE TITLE
Airship interface with generic container is not passing hostnetworking

### ISSUE THREAD

**Issue by teoyaomiqui** [airshipit/airshipctl#512]
**Describe the bug**
When creating a phase with GenericContainer executor spec.HostNetwork setting is ignored by airship container.

**Steps To Reproduce**
Create a phase and executor:

```
apiVersion: airshipit.org/v1alpha1
kind: Phase
metadata:
  name: kubectl-wait-node-ephemeral
  clusterName: ephemeral-cluster
config:
  executorRef:
    apiVersion: airshipit.org/v1alpha1
    kind: GenericContainer
    name: kubectl-get-node
  documentEntryPoint: ephemeral/initinfra-networking
---
apiVersion: airshipit.org/v1alpha1
kind: GenericContainer
metadata:
  name: kubectl-get-node
  labels:
    airshipit.org/deploy-k8s: "false"
spec:
  image: quay.io/airshipit/toolbox:latest
  hostNetwork: true
configRef:
  kind: ConfigMap
  name: kubectl-get-node
  apiVersion: v1
```

1) Run `airshipctl phase run kubectl-wait-node-ephemeral` command

**Expected behavior**
Airship successfully reaching the ephemeral cluster and waiting for the node to come up

**Actual behavior**
Airship container has no host networking, and fails to reach k8s node
