### ISSUE TITLE
Airship interacting with generic container hangs

### ISSUE THREAD

**Issue by teoyaomiqui** [airshipit/airshipctl#513]
**Describe the bug**
Sometimes airshipctl would hang indefinitely without actually starting the docker container.

**Steps To Reproduce**
The bug is floating, and it seems to be working, however, sometimes it hags.

Create a phase with the executor of type airship:

```
---
apiVersion: airshipit.org/v1alpha1
kind: GenericContainer
metadata:
  name: kubectl-wait-node
  labels:
    airshipit.org/deploy-k8s: "false"
spec:
  image: quay.io/airshipit/toolbox:latest
  hostNetwork: true
configRef:
  kind: ConfigMap
  name: kubectl-wait-node
---
apiVersion: airshipit.org/v1alpha1
kind: Phase
metadata:
  name: kubectl-wait-node-ephemeral
  clusterName: ephemeral-cluster
config:
  executorRef:
    apiVersion: airshipit.org/v1alpha1
    kind: GenericContainer
    name: kubectl-wait-node
  documentEntryPoint: ephemeral/initinfra-networking
```

run the phase:
```
# airshipctl phase run kubectl-wait-node-ephemeral
```

**Expected behavior**
airshipctl tries to execute script specified in `kubectl-wait-node` ConfigMap

**Actual behavior**
airshipctl hangs indefinitely

**Environment**
- airshipctl Version: v2.0
- Operating System: Ubuntu 20.04
- Kernel version: 5.4.0-70-generic
- Kubernetes Version: 1.19
- Go version: 1.13
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM): VM with 2 CPU and 8 GB
