### ISSUE TITLE
Enhance Gating to Test KRM Function Updates

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#524]
**Problem description**
Current airshipctl gating uses pinned versions of the KRM function images rather than building the KRM functions from the current code.  Therefore, code updates to the KRM functions are not being tested in the gate scripts and undetected problems can be pushed to image repositories. 

**Proposed change**
Need a plan for testing the KRM functions in gate scripts.  Some options:

- Run airshipctl gating using images built off current code rather than pinned image versions
- Move each KRM function into its own repo with its own specific testing

Adding "design needed" label for discussion during a design call.

**Comment by sirajyasin** [comment]
@lb4368 ,I can start working on this after the design discussion.

My Initial thought for implementation:
1. Have a nightly job in Third Party Jenkins to validate the test-site deployment in airshipctl using latest version of plugins.
2. In the Pipeline just after cloning the code, execute "./tools/deployment/update-krm-images" to set the new plugin images to use latest instead of v2.
3. Execute remaining steps to validate deployment.

**Comment by aostapenko** [comment]
+ @ak3216 
We should switch to moving tag (latest) and build images in the same buildset, share them via buildset registry and use them during the testing.
Similar to what we're planning to try for airship/images https://github.com/airshipit/images/issues/18
It may actually make a sense for me to start it here. Since it's not a trivial solution POC may be required.

**Comment by ak3216** [comment]
@aostapenko this one is yours.

**Comment by lb4368** [comment]
@aostapenko  This issue is added to the agenda for 4/29/21 design call for discussion

**Comment by seaneagan** [comment]
# Proposal: Externalize krm function versions

Managing the krm function versions would become a lot easier if we can specify them in a single place, outside of the manifests, rather than at each call site within the manifests as we currently do. This could be accomplished by having the manifests (airshipctl, treasuremap, downstream) reference krm function image tags which are only available locally and not in a remote repo such as quay. For example it could be called:

`localhost/replacement-transformer:latest`

Then before running airshipctl we set those tags to whatever is desired. For airshipctl gates we could build the krm functions from the patchset with the above tag format applied. For treasuremap gates we could do the same, except pointed at the AIRSHIPCTL_REF that we are pinned to in treasuremap, or we could pull the same SHA for each krm function from quay and `docker tag` it with the above tag format.

This could be formalized by creating a script (could eventually be built into airshipctl) which consumes *local* container image overrides, i.e. those used by the container runtime used by airshipctl itself. The script would optionally pull the source image tags from remote repos (if they are not already available due to having built them locally), and then `docker tag` each source image tag with a override image tag, particularly the ones used in the manifests. Example override map, as applicable to a treasuremap release:

```yaml
quay.io/airshipit/replacement-transformer:v2.1.0: localhost/replacement-transformer:latest
quay.io/airshipit/templater:v2.1.0: localhost/templater:latest
quay.io/airshipit/cloud-init:v2.1.0: localhost/cloud-init:latest
gcr.io/kpt-fn-contrib/sops:v0.1.0: localhost/sops:latest
```

Currently the airship-owned krm functions have their own independent release process, but if we wanted to simplify we could just release those in lock step with airshipctl. In this case we could even parameterize the override map such that it is driven by the AIRSHIPCTL_REF:

```yaml
quay.io/airshipit/replacement-transformer:${AIRSHIPCTL_REF}: localhost/replacement-transformer:latest
quay.io/airshipit/templater:${AIRSHIPCTL_REF}: localhost/templater:latest
quay.io/airshipit/cloud-init:${AIRSHIPCTL_REF}: localhost/cloud-init:latest
gcr.io/kpt-fn-contrib/sops:v0.1.0: localhost/sops:latest
```

In this case AIRSHIPCTL_REF can drive the krm function version in both treasuremap master (airshipctl commit SHA) and on release branches (airshipctl release tag e.g. v2.1.0).

Downstream use cases can similarly take advantage of this by pointing to alternate (e.g. internal) image locations in their image overrides map, or just build them locally from the AIRSHIPCTL_REF as well if desired.

**Comment by teoyaomiqui** [comment]
@seaneagan, just a thought.
What if we create a specific release repository, like treasuremap, where we put all plugin declaration. Add this repository as a separate repository in arishipctl.config.manifest.repository:

This new repository will have its own tags that would 

```yaml
manifests:
  site-one-manifest:
    inventoryRepositoryName: ""
    metadataPath: manifests/site/reference-airship-core/metadata.yaml
    phaseRepositoryName: primary
    repositories:
      airshipctl:
        checkout:
          branch: master
        url: https://review.opendev.org/airship/airshipctl
      primary:
        checkout:
          branch: master
        url: https://review.opendev.org/airship/treasuremap
      **kustomize-plugins**:
        checkout:
          tag: "v2.1.3"
       url: https://review.opendev.org/airship/plugin-resources
    targetPath: /home/ubuntu/airship
```

This **kustomize-plugins** repo holds all plugin declaration in a nice directory structure that is easy to understand and maintain.

We would have one copy of the repository with a downstream set of images; 
We would have another one with an upstream set of images in upstream.

This would also cover unique sets of variables as well per deployment. Managing images, in this case, would be much easier, I think. We will have one place for plugin declarations; nothing else will be there; they will be used as libraries.
