### ISSUE TITLE
Fix `airshipctl config get-context` maximum args

### ISSUE THREAD

**Issue by SirishaGopigiri** [airshipit/airshipctl#526]
**Bug Description**
The `airshipctl config get-context` command currently doesn't limit on the number of arguments that can be passed. So when we pass more that one parameter(example as show below) it returns all the contexts.

`airshipctl config get-context ephemeral-cluster target-cluster`

**Steps To Reproduce**
Sample airship config file
```
apiVersion: airshipit.org/v1alpha1
managementConfiguration:
  dummy_management_config:
    type: redfish
    insecure: true
    useproxy: false
    systemActionRetries: 30
    systemRebootDelay: 30
contexts:
  test-cluster:
    contextKubeconf: ephemeral-cluster_ephemeral
    manifest: dummy_manifest
    managementConfiguration: dummy_management_config
  ephemeral-cluster:
    contextKubeconf: ephemeral-cluster_ephemeral
    manifest: dummy_manifest
    managementConfiguration: dummy_management_config
  target-cluster:
    contextKubeconf: target-cluster_target
    manifest: dummy_manifest
    managementConfiguration: dummy_management_config
currentContext: ephemeral-cluster
kind: Config
manifests:
  dummy_manifest:
    phaseRepositoryName: primary
    repositories:
      primary:
        checkout:
          branch: master
          force: false
          remoteRef: ""
          tag: ""
        url: https://review.opendev.org/airship/airshipctl
    metadataPath: manifests/site/test-site/metadata.yaml
    targetPath: xyz
```

For the above config file if we issue `airshipctl config get-context ephemeral-cluster target-cluster` it returns all the contexts. I think it would be better if we accept only one argument/parameter.

**Expected behavior**
Current output
```
managementConfiguration: dummy_management_config
manifest: dummy_manifest

managementConfiguration: dummy_management_config
manifest: dummy_manifest

managementConfiguration: dummy_management_config
manifest: dummy_manifest
```
Expected output:
```
accepts at most 1 arg(s), received 2
```

Simple fix would be to add `Args: cobra.MaximumNArgs(1),` in the cobra command

**Environment**
- airshipctl Version: master branch
- Operating System: macOS
- Go version: 1.15.6
