### ISSUE TITLE
Flux source-controller Function Proxy Var Replacement Not Working

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#550]
**Describe the bug**
When rendering the _source-controller_ manifest function with the _env-vars_ replacements, the proxy environment variables are not included in the environment for the _source-controller_ Deployment resource.  Because of this, when applying this manifest function behind a proxy, HelmRepository resources created do not have access to URLs through the proxy.

**Steps To Reproduce**
Run the following steps on a server that accesses the internet through a proxy.  

1. Ensure that HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables are properly set.
2. Configure `~/.airship/config` for the airshipctl test-site (`manifests/site/test-site`)
3. Run `airshipctl phase render initinfra-target`
4. In result output notice there is no proxy env values set in yaml path spec.template.spec.containers[name=manager].env for proxy setting in the resulting Deployment/source-controller resource.  This appears to be because there is no matching placeholders in the `upstream/manager/deployment.yaml` spec to be replaced using `replacements/env-vars.yaml` within the _source-controller_ function.

**Expected behavior**
Expecting resulting source-controller deployment to include proxy env settings to match HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables:
```
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: http_proxy
          value: <HTTP_PROXY value>
        - name: https_proxy
          value: <HTTPS_PROXY value>
        - name: no_proxy
          value: <NO_PROXY value>
```
**Environment**
- airshipctl Version: 1f5dbf8645f24124634fbbc4389a9d7a27008523
- Operating System: 
- Kernel version:
- Kubernetes Version:
- Go version:
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM):
