### ISSUE TITLE
Docker Provider - Force to Use Quay.io Clusterctl image

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#642]
**Problem description (if applicable)**
In order to fix issue when uplifting to CAPI v0.4.2 (#518), we need the Docker provider to use the krm supporting clusterctl: 0.3.22 version instead of latest.  The reason is when uplifting to CAPI v0.4.2, the clusterctl krm image is build using clusterctl:0.4.2 binary, which may be causing Zuul to fail during docker provider test.

**Proposed change**
The proposed approach (but not limited to) is to create a strategic merge on the docker-test-site level for the clusterctl executor.

```
apiVersion: airshipit.org/v1alpha1
kind: GenericContainer
metadata:
  name: clusterctl
  labels:
    airshipit.org/deploy-k8s: "false"
spec:
  type: krm
  image: localhost/clusterctl:latest #  replace by e.g., quay.io/airshipit/clusterctl:eb9ac97ce207542e1e4d3b363963bfc5f0847096
  hostNetwork: true
```
