### ISSUE TITLE
Panic on `airshipctl bootstrap remotedirect`

### ISSUE THREAD

**Issue by ian-howell** [airshipit/airshipctl#65]
**Describe the bug**
There is currently a panic when running `airshipctl bootstrap remotedirect` when the user has a malformed config file

**Steps To Reproduce**
```
make install
DEMO=$(mktemp -d)
mkdir "$DEMO/.airship"


cat << EOF > "$DEMO/.airship/config"
apiVersion: airshipit.org/v1alpha1
clusters:
  default:
    cluster-type:
      target:
        bootstrap-info: "default"
        cluster-kubeconf: default_target
contexts:
  default:
    context-kubeconf: default_target
    manifest: default
current-context: "default"
kind: Config
manifests:
  default:
    repository:
      checkout:
        branch: master
        commit-hash: master
        force: false
        remote-ref: master
        tag: ""
      url: https://opendev.org/airship/treasuremap
    target-path: /tmp/airship
modules-config:
  bootstrapInfo:
    default:
      builder:
        networkConfigFileName: network-config
        outputMetadataFileName: output-metadata.yaml
        userDataFileName: user-data
      container:
        containerRuntime: docker
        image: quay.io/airshipit/isogen:latest
        volume: /srv/iso:/config
users:
  admin: {}
EOF


cat << EOF > "$DEMO/.airship/kubeconfig"
apiVersion: v1
clusters:
- cluster:
    server: https://172.17.0.1:6443
  name: default_target
contexts:
- context:
    cluster: default_target
    user: admin
  name: default
current-context: ""
kind: Config
preferences: {}
users:
- name: admin
  user:
    username: airship-admin
EOF


cat << EOF > "$DEMO/kustomization.yaml"
resources:
  - host.yaml
EOF


cat << EOF > "$DEMO/host.yaml"
---
apiVersion: v1
kind: Secret
metadata:
  name: example-baremetalhost-secret
type: Opaque
data:
  username: user
  password: pass
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: example-baremetalhost
  labels:
    airshipit.org/ephemeral: "true"
spec:
  online: true
  bmc:
    address: ipmi://192.168.122.1:6230
    credentialsName: example-baremetalhost-secret
EOF


airshipctl bootstrap remotedirect --airshipconf "$DEMO/.airship/config" --kubeconfig "$DEMO/.airship/kubeconfig"
```

Note that  `modules-config.bootstrapInfo.default` is missing the `remoteDirect` field.

**Expected behavior**
`airshipctl` should not panic, but should provide a clear and concise .error message
